name: Publish Module to FoundryVTT Website

on:
  release:
    types: [published]

jobs:
  publish-module-to-foundryvtt:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Module to FoundryVTT Website
        id: publish-to-foundry-website
        uses: cs96and/FoundryVTT-release-package@v1.0.2
        with:
          package-token: ${{ secrets.PACKAGE_TOKEN }}
          manifest-url: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.json
          notes-url: https://github.com/${{github.repository}}/releases/tag/${{github.event.release.tag_name}}
